### ISSUE TITLE
在 AUR 上打了个包

### ISSUE THREAD

**Issue by ayalhw** [iotang/Project_LemonLime#11]
在 AUR 上打了个包，方便 Arch 用户安装

https://aur.archlinux.org/packages/lemon-lime-git/

https://aur.archlinux.org/packages/lemon-lime/

**Comment by iotang** [comment]
老哥太强悍了

**Comment by ayalhw** [comment]
> 老哥太强悍了

Arch 的打包是个发行版里几乎最简单的，我很菜的
