### ISSUE TITLE
无法测评程序

### ISSUE THREAD

**Issue by liaojiqing2012** [iotang/Project_LemonLime#12]
一旦测评就会弹出
由于找不到libgcc_s_dw2-1.dll，无法继续执行代码，重新安装程序可能会解决问题。
![TIM截图20200210133815](https://user-images.githubusercontent.com/12479768/74123748-b64b6600-4c0a-11ea-8ab3-2e247757354a.png)

由于找不到libstdc++-6.dll，无法继续执行代码，重新安装程序可能会解决问题。
![image](https://user-images.githubusercontent.com/12479768/74123741-afbcee80-4c0a-11ea-8f40-da1c3e50c321.png)

**Comment by iotang** [comment]
编译选项加上 `-static` 试一下

**Comment by Dust1404** [comment]
编译时加入 -static 选项可以解决。

看来没有 merge [这个](https://github.com/Dust1404/Project_LemonPlus/commit/ab07ca289f9ddea5e8cff12c68313c25ef85bc98)

**Comment by iotang** [comment]
我好想把这个东西在[这里](https://github.com/iotang/Project_LemonLime/blob/master/addcompilerwizard.cpp)写了啊。。。

**Comment by Dust1404** [comment]
`JudgingThread::runProgram()` 中通过 `CreateProcess` 创建进程时环境变量中用 `\0` 隔开。

在 `judgingthread.cpp` 第 860 行应该为 `.join('\0')`，不能为 `QString("\0")`。

可能是这个原因。
