### ISSUE TITLE
Test In Arch Linux @ 2020-2-22

### ISSUE THREAD

**Issue by ayalhw** [iotang/Project_LemonLime#14]
我在2020-2-22于本人新安装的Arch Linux上进行了测试，目前看来功能一切正常

|系统名称|版本号|位数|DE / WM|
|:--:|:--:|:--:|:--:|
|Arch|2020-2-22|64|KDE|

另外我是来请罪的，因为某些愚蠢的原因，我将AUR上git包中的文件名写错，致使build failed，在此道歉，现已修复

**Comment by ayalhw** [comment]
另外您release的时候不用专门打源码包，GitHub会自动生成release时的.tar.gz和.zip格式的源码包

**Comment by iotang** [comment]
其实我 release 的重点是 Windows 打包版本。。。
源码包是我强迫症犯了。。。
