### ISSUE TITLE
[Advice]可以利用 GitHub Action 自动发布 windows安装包

### ISSUE THREAD

**Issue by ayalhw** [iotang/Project_LemonLime#15]
可以利用GitHub Action 自动发布 windows安装包
以下项目提供了action
https://github.com/jurplel/install-qt-action

**Comment by iotang** [comment]
还有这种东西，我去研究一下

**Comment by ayalhw** [comment]
https://zhuanlan.zhihu.com/p/92733295

https://zhuanlan.zhihu.com/p/95926317

**Comment by ayalhw** [comment]
建议姐姐吧tag稳定成数字……
我太难了……

**Comment by iotang** [comment]
有几个奇怪的问题
1. Tag 名字取太长会导致 Validation Failed
2. MacOS 无论怎样都会随机 Validation Failed

**Comment by ayalhw** [comment]
> 有几个奇怪的问题
> 
> 1. Tag 名字取太长会导致 Validation Failed
> 2. MacOS 无论怎样都会随机 Validation Failed

1.使用短tag可以解决
2.看看能否寻找规律……对同样地tag多次触发action试试？

**Comment by ayalhw** [comment]
> 有几个奇怪的问题
> 
> 1. Tag 名字取太长会导致 Validation Failed
> 2. MacOS 无论怎样都会随机 Validation Failed

https://github.com/iotang/Project_LemonLime/blob/master/.github/workflows/macos.yml#L85
这一部分有问题？

**Comment by iotang** [comment]
现在问题变成了这样
1. 虽然 MacOS 的 queryRelease 和 Windows 的是一样的，但是 MacOS 总会抛 403 错误，但是 Windows 不会
2. 发布 tag 后 MacOS 第一遍 Action 必定失败，错误就是 403；重跑大概率失败（403），~~小概率主站抛 500~~

**Comment by water-lift** [comment]
要不试试travis ci啥的？------------------ 原始邮件 ------------------
发件人: "iotang"<notifications@github.com>
发送时间: 2020年2月28日(星期五) 上午8:24
收件人: "iotang/Project_LemonLime"<Project_LemonLime@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [iotang/Project_LemonLime] [Advice]可以利用 GitHub Action 自动发布 windows安装包 (#15)



现在问题变成了这样
  
虽然 MacOS 的 queryRelease 和 Windows 的是一样的，但是 MacOS 总会抛 403 错误，但是 Windows 不会
 
发布 tag 后 MacOS 第一遍 Action 必定失败，错误就是 403；重跑大概率失败（403），小概率主站抛 500
  
&mdash;

**Comment by iotang** [comment]
等会，MacOS 哪来的 Powershell

**Comment by iotang** [comment]
经验：不要重复发明轮子。
搞定。

**Comment by ayalhw** [comment]
@iotang 好像缺个rpm包……

**Comment by iotang** [comment]
这个真的有必要吗…

**Comment by ayalhw** [comment]
好像是没有必要……
