### ISSUE TITLE
lemonlime是OJ还是评测机?

### ISSUE THREAD

**Issue by MX-Qulin** [iotang/Project_LemonLime#16]
lemonlime是OJ还是评测机?能在服务器上跑吗?
另:如何安装?推荐写个wiki~
Thank You :)

**Comment by iotang** [comment]
LemonLime 只是一个单机测试系统。装有 LemonLime 的机器可以暂且称作评测机。
如果服务器上想跑的话，服务器上面得有 GUI。不过这不太可能。
安装教程在 README 里面。

**Comment by water-lift** [comment]
既不是oj也不是评测机。cena（或者lemon）用过吧？------------------ 原始邮件 ------------------
发件人: "MX-Qulin"<notifications@github.com>
发送时间: 2020年2月24日(星期一) 晚上6:31
收件人: "iotang/Project_LemonLime"<Project_LemonLime@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [iotang/Project_LemonLime] lemonlime是OJ还是评测机? (#16)



lemonlime是OJ还是评测机?能在&#x670D;务器上跑吗?
 另:如何安装?推荐写个wiki~
 Thank You :)
 
&mdash;

**Comment by MX-Qulin** [comment]
emmm    类似于 北京航空航天大学的 arbiter?

**Comment by water-lift** [comment]
对的------------------ 原始邮件 ------------------
发件人: "MX-Qulin"<notifications@github.com>
发送时间: 2020年2月24日(星期一) 晚上6:38
收件人: "iotang/Project_LemonLime"<Project_LemonLime@noreply.github.com>;
抄送: "water_lift"<2677294549@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iotang/Project_LemonLime] lemonlime是OJ还是评测机? (#16)



emmm    类似于 北京航空航天大学的 arbiter?
 
&mdash;

**Comment by iotang** [comment]
对就是那个东西。
LemonLime 的一个愿望就是把 Arbiter 按在地上摩擦。

**Comment by MX-Qulin** [comment]
Thank you :) 希望你们的愿望早日实现(*^_^*)

**Comment by water-lift** [comment]
淦邮件回复咋用啊

**Comment by iotang** [comment]
实不相瞒，除了没有被 CCF 采用之外，LemonLime 已经完爆 Arbiter 了

**Comment by water-lift** [comment]
格式好诡异 ------------------ 原始邮件 ------------------
发件人: "MX-Qulin"<notifications@github.com>
发送时间: 2020年2月24日(星期一) 晚上6:40
收件人: "iotang/Project_LemonLime"<Project_LemonLime@noreply.github.com>;
抄送: "water_lift"<2677294549@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iotang/Project_LemonLime] lemonlime是OJ还是评测机? (#16)



Closed #16.
 
&mdash;

**Comment by water-lift** [comment]
cena和arbiter相比呢？（lemon和arbiter就不用比了

> 实不相瞒，除了没有被 CCF 采用之外，LemonLime 已经完爆 Arbiter 了

**Comment by MX-Qulin** [comment]
> 
> 
> 实不相瞒，除了没有被 CCF 采用之外，LemonLime 已经完爆 Arbiter 了

没试过,因为arbiter太烂所以先赞同一把

**Comment by iotang** [comment]
Cena 支持 Linux 吗

**Comment by water-lift** [comment]
cena毕竟是开源的。。。理论上应该能支持linux。。。但那玩意也没个说明。。。  ------------------ 原始邮件 ------------------
发件人: "iotang"<notifications@github.com>
发送时间: 2020年2月24日(星期一) 晚上6:44
收件人: "iotang/Project_LemonLime"<Project_LemonLime@noreply.github.com>;
抄送: "water_lift"<2677294549@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iotang/Project_LemonLime] lemonlime是OJ还是评测机? (#16)



Cena 支持 Linux 吗
 
&mdash;

**Comment by iotang** [comment]
Cena 就一个联网功能还有点用…

**Comment by water-lift** [comment]
> Cena 就一个联网功能还有点用…

实际上那玩意我就没见有用过的

**Comment by Dust1404** [comment]
没记错 cena 好像是 win32 平台开发的，原生不支持跨平台。但是我看 github 上有一个 CenaPlus 的后续维护项目，相当于是一个 OJ 了。

**Comment by iotang** [comment]
刚刚翻到一个项目 oi-archive/cena，声称是“Real Cena Local Judge”，不过连个 README 都没有，太寒碜了

**Comment by water-lift** [comment]
> 没记错 cena 好像是 win32 平台开发的，原生不支持跨平台。但是我看 github 上有一个 CenaPlus 的后续维护项目，相当于是一个 OJ 了。

然而6年没更新了

**Comment by Dust1404** [comment]
cena 最早是在 google-code 上维护的，github 上是搬运来的。

**Comment by iotang** [comment]
好像 Lemon 本原版也是在 google-code 上面有

**Comment by Dust1404** [comment]
> 好像 Lemon 本原版也是在 google-code 上面有

Lemon 作者把导入到 github 上来了
