### ISSUE TITLE
暗色主题增加需求

### ISSUE THREAD

**Issue by Itst-I-hate-duplicate-name** [iotang/Project_LemonLime#17]
在 Linux Mint 上选了一个主题商城的暗色主题，果不其然评分界面亮度异常的高，眼睛不好的群众表示瞎了。而且感觉字体灰度比较低所以不太容易看清。

效果图：

![TIM图片20200225214722.png](https://i.loli.net/2020/02/25/4ov5FqKCMXSwtRi.png)

最新发现的一个 bug 是超链接因为颜色过深也会增加阅读难度？

![TIM图片20200225221456.png](https://i.loli.net/2020/02/25/sDkUoF7tBKPRO3c.png)

**Comment by iotang** [comment]
憋说了，我当初画 UI 的时候压根就没想过有暗色主题这回事
不信你可以看按钮旁边的图标几乎全是黑色的
