### ISSUE TITLE
[Release] Action 中 Ubuntu 编译完未打包和推送

### ISSUE THREAD

**Issue by ayalhw** [iotang/Project_LemonLime#22]
Action 中 Ubuntu 编译完未打包和推送

**Comment by iotang** [comment]
你是说打成一个 deb 包？

**Comment by ayalhw** [comment]
> 你是说打成一个 deb 包？

能 deb 最好，没有的话把二进制打成压缩包丢上去也行

**Comment by iotang** [comment]
好像这个东西不是很有必要，不过有时间会做的

**Comment by ayalhw** [comment]
Add in https://github.com/iotang/Project_LemonLime/commit/480953127d32f1909d4d41917f261266fdb58562
Closes.
