### ISSUE TITLE
windows版内存消耗显示为0

### ISSUE THREAD

**Issue by totorato** [iotang/Project_LemonLime#25]
评测结果中所有的内存消耗均显示为0.000MB
windows10

**Comment by iotang** [comment]
具体是测什么题目啊

**Comment by totorato** [comment]
我测了传统题和通信题，都是0MB



在 2020-04-11 13:51:24，"iotang" <notifications@github.com> 写道：

具体是测什么题目啊

**Comment by totorato** [comment]
![图片](https://s1.ax1x.com/2020/04/14/Jp8ZCV.png)

**Comment by iotang** [comment]
问题不能复现。
你是下载现成的包，还是下载源码后自行编译的？
使用的编译器是什么？

**Comment by totorato** [comment]
是下载的现成的包，v0.1.3



在 2020-04-15 19:36:14，"iotang" <notifications@github.com> 写道：

问题不能复现。
你是下载现成的包，还是下载源码后自行编译的？
使用的编译器是什么？

**Comment by Cekavis** [comment]
我windows v0.1.4现成的包测传统题也是这样... 本来都没发现（

**Comment by iotang** [comment]
草，这个问题只有在打包的程序里才能发生
~~包下载慢死我了~~

**Comment by Cekavis** [comment]
> 草，这个问题只有在打包的程序里才能发生
> ~包下载慢死我了~

我3.12的result就有这个问题，但是似乎没人发现

**Comment by iotang** [comment]
稍等，某热心老哥正在构建 msvc 环境，马上就可以开始修锅（？）
已知如果用 mingw 编译的话将不会出现这个问题

**Comment by iotang** [comment]
在本地 msvc 上问题竟然不能重现

**Comment by iotang** [comment]
有个小问题，Windows Server 和 Windows Client 是不是有一些 WinAPI 不一样啊？
在本地完全无法复现问题。

**Comment by iotang** [comment]
好像修好了？

**Comment by totorato** [comment]
修好啦~太棒了

**Comment by iotang** [comment]
如果问题确实不再出现的话，就把这个 issue 关了吧

**Comment by Cekavis** [comment]
我没试过，如果还有问题可以再开（（
