### ISSUE TITLE
程序的运行时间波动非常大

### ISSUE THREAD

**Issue by zhongyuwei** [iotang/Project_LemonLime#32]
1. 程序的运行时间会严重受到电脑当时同步运行的程序的影响（关掉备份与同步程序之后，可能会快 1s 左右）
2. 在同样的条件下，程序的运行时间也会有很大的波动。这个视频中，试题 tree 的配置为每个测试点时间 2250ms, 空间 1024MB，连续 4 次测试 std 的结果差异较大。[视频链接](https://drive.google.com/open?id=1_1IFD-KDvrauq3rBqPTtcKVHTTifd3sU)

**Comment by zhongyuwei** [comment]
使用 lemon 评测也存在这个问题。。。有什么比较好的解决办法吗？/kel

**Comment by iotang** [comment]
无论在什么情况，选手程序都要和其它所有进程抢 CPU，至于抢不抢得过完全随机
可能你开个游戏模式能缓解这个问题
（别发谷歌链接啊。。。我这儿网络情况很差的

**Comment by ayalhw** [comment]
可以配置让评测独占一个CPU核心，这样理论上能有效改善

**Comment by iotang** [comment]
独占 CPU 核心这种事情好像得动内核吧…

**Comment by ayalhw** [comment]
> 独占 CPU 核心这种事情好像得动内核吧…

Windows好像有个CPU亲和性可以做到，Linux搞内核参数很简单，但是似乎都要手工操作

**Comment by ayalhw** [comment]
> Moon Mid, [25.05.20 20:13]
> 能不能限制某个进程只能在某个核上运行呢？
> 
> 依云, [25.05.20 20:13]
> [回复 Moon Mid]
> 能啊
> 
> 依云, [25.05.20 20:13]
> 你把它先 pin 上去，然后不给它设置的权限，它就下不来了
> 
> 依云, [25.05.20 20:14]
> 其实一般进程不会自己择核的，都是听内核的调度
> 
> 依云, [25.05.20 20:14]
> 所以 taskset 一下就挺好了
> 
> 依云, [25.05.20 20:14]
> 只有像 nginx 这种多进程 worker 又需要高性能的才会主动设置用哪个核

摘自Arch Linux CN群内讨论，可供参考
