### ISSUE TITLE
也许需要一个 .clang-format 来统一代码风格

### ISSUE THREAD

**Issue by ayalhw** [iotang/Project_LemonLime#35]
RT, 虽然主力开发者只有 iotang 一个人……

**Comment by iotang** [comment]
啊，我都是用 astyle 的
让我先研究一下 clang-format

**Comment by iotang** [comment]
Clang Format 牛逼

**Comment by ayalhw** [comment]
cpeditor 项目的这个用法似乎不错 https://github.com/ouuan/cpeditor/blob/master/.github/workflows/check_format.yml
