### ISSUE TITLE
[Release][Advice] 建议增加Win32的二进制文件?

### ISSUE THREAD

**Issue by Oneton429** [iotang/Project_LemonLime#42]
机房的电脑是32位的差评  
这导致LemonLime没法运行  
(要知道很多机房为了安全是在虚拟机里运行学生用的系统，为了性能会装32位系统)(超小声)

**Comment by ayalhw** [comment]
看来需要改下action……需要先打个patch上去……

**Comment by ayalhw** [comment]
等我回家拿到电脑搞下

**Comment by ayalhw** [comment]
https://github.com/Qv2ray/Qv2ray/blob/master/.github/workflows/nsis.yml

**Comment by ayalhw** [comment]
@Oneton429 
已添加，参见 https://github.com/iotang/Project_LemonLime/releases/tag/v0.2.3rc2
此外每次 push 的 CI 也会生成一份，可以在 GitHub Actions 界面自取，例如： 
https://github.com/iotang/Project_LemonLime/actions/runs/182469235
https://github.com/iotang/Project_LemonLime/actions/runs/182469240
https://github.com/iotang/Project_LemonLime/actions/runs/182469243

**Comment by Oneton429** [comment]
好的好的
谢谢dalao
