### ISSUE TITLE
希望统一 Release 中的文件名

### ISSUE THREAD

**Issue by ChungZH** [iotang/Project_LemonLime#43]
如 `lemon-Windows-64.zip`，而不是现在的 `5.15.0-desktop-win64_msvc2019_64.zip`，这样能比较方便打包者。不然的话万一 Qt 版本更新了也很难再匹配这个新的文件名 :joy:

修改此处即可 

https://github.com/iotang/Project_LemonLime/blob/f8de93abbdb3b4e28de0beb429490a1ff5246495/.github/workflows/windows.yml#L101-L109

**Comment by ayalhw** [comment]
很抱歉当初没考虑到这点因此给您造成了麻烦……非常抱歉

**Comment by ChungZH** [comment]
不不不不不不，主要是我太菜了，实在没办法才来找你们 :joy: 辛苦了

**Comment by ayalhw** [comment]
Done.
https://github.com/iotang/Project_LemonLime/blob/master/.github/workflows/windows.yml#L104
但你可能需要等一等 0.2.3（~~没错，我不遵守 semver 的~~

**Comment by ChungZH** [comment]
okok，太棒力！

**Comment by ayalhw** [comment]
> okok，太棒力！

等会儿就把你的 bucket 塞进 README
另外我把32位的编译加上了……下个版本开始应该就也有32位的了，麻烦注意下

**Comment by ChungZH** [comment]
好的好的！明天俺跟进跟进

**Comment by ayalhw** [comment]
加好了 https://github.com/iotang/Project_LemonLime/commit/28ba8ca6bf98c907acdad75d176dbef37918399c

**Comment by ChungZH** [comment]
https://github.com/ChungZH/peach/commit/55ca62d861ee56004931273ec8c19884dea7a890

等到下一个 Release 发布之后就可以加上 32 位的情况啦！
