### ISSUE TITLE
0.2.2版本 Deepin V20编译报错

### ISSUE THREAD

**Issue by Bluequarks** [iotang/Project_LemonLime#50]
报错信息:
CMake Error at CMakeLists.txt:16 (add_subdirectory):
  The source directory

    /home/zly/Downloads/Project_LemonLime-0.2.2/singleapplication

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/zly/Downloads/Project_LemonLime-0.2.2/CMakeFiles/CMakeOutput.log".
漏提交文件了?

**Comment by ayalhw** [comment]
（看样子是 GitHub Release 的源码包没打包 submodule, 我看看有什么办法吗

**Comment by ayalhw** [comment]
[Project_LemonLime.tar.gz](https://github.com/iotang/Project_LemonLime/files/4977484/Project_LemonLime.tar.gz)

提供一份源码，以后的 release 会带一份完整源码了

**Comment by Bluequarks** [comment]
谢谢,然而还是报错了:
CMake Error: The source directory "/home/zly/Downloads/Project_LemonLime/--build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
是在执行"cmake . --build"时出现的

**Comment by ayalhw** [comment]
> 谢谢,然而还是报错了:
> CMake Error: The source directory "/home/zly/Downloads/Project_LemonLime/--build" does not exist.
> Specify --help for usage, or press the help button on the CMake GUI.
> 是在执行"cmake . --build"时出现的

淦，我README写错了
```
cmake --build .
```
多谢提醒

**Comment by ayalhw** [comment]
如果你是0.2.3rc1 之后的版本，可以将cmake那两行换为
```
cmake . -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_DEB=ON
cmake --build . --target package --parallel $(nproc)
```
直接生成 deb 包
参考 https://github.com/iotang/Project_LemonLime/blob/master/.github/workflows/cpack-deb.yml#L54-L55

**Comment by Bluequarks** [comment]
我是DeepinV20,默认的Qt是5.11,使用0.2.3rc2源码,使用您推荐的deb方式编译还是出错了:
# Since Qt 5.13
has_swapItemsAt=(  'contest.cpp'
                   'contestant.cpp'
                   )

for i in "${has_swapItemsAt[@]}"; do
    sed -i 's/swapItemsAt/swap/g' "$1"/"$i"
done
sed：无法读取 /home/zly/Downloads/Project_LemonLime-0.2.3rc2/contest.cpp：没有那个文件或目录
-- Configuring incomplete, errors occurred!
See also "/home/zly/Downloads/Project_LemonLime-0.2.3rc2/CMakeFiles/CMakeOutput.log".

**Comment by Bluequarks** [comment]
啊这,我自己改了改文件修好了上面的bug,但是又有新bug了(在cmake build过程中):
[16/49] Building CXX object CMa...es/lemon.dir/src/settings.cpp.o
FAILED: CMakeFiles/lemon.dir/src/settings.cpp.o 
/usr/bin/c++  -DQAPPLICATION_CLASS=QApplication -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I. -Ilemon_autogen/include -Isrc -I3rdparty/SingleApplication -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -O3 -DNDEBUG   -fPIC -std=gnu++17 -MD -MT CMakeFiles/lemon.dir/src/settings.cpp.o -MF CMakeFiles/lemon.dir/src/settings.cpp.o.d -o CMakeFiles/lemon.dir/src/settings.cpp.o -c src/settings.cpp
src/settings.cpp: In member function ‘void Settings::setInputFileExtensions(const QString&)’:
src/settings.cpp:251:50: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  inputFileExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                                  ^~~~~~~~~~~~~~
src/settings.cpp: In member function ‘void Settings::setOutputFileExtensions(const QString&)’:
src/settings.cpp:256:51: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  outputFileExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                                   ^~~~~~~~~~~~~~
src/settings.cpp: In member function ‘void Settings::swapCompiler(int, int)’:
src/settings.cpp:294:17: error: ‘class QList<Compiler*>’ has no member named ‘swapItemsAt’
    compilerList.swapItemsAt(a, b);
                 ^~~~~~~~~~~
[19/49] Building CXX object CMa...es/lemon.dir/src/compiler.cpp.o
FAILED: CMakeFiles/lemon.dir/src/compiler.cpp.o 
/usr/bin/c++  -DQAPPLICATION_CLASS=QApplication -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I. -Ilemon_autogen/include -Isrc -I3rdparty/SingleApplication -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -O3 -DNDEBUG   -fPIC -std=gnu++17 -MD -MT CMakeFiles/lemon.dir/src/compiler.cpp.o -MF CMakeFiles/lemon.dir/src/compiler.cpp.o.d -o CMakeFiles/lemon.dir/src/compiler.cpp.o -c src/compiler.cpp
src/compiler.cpp: In member function ‘void Compiler::setSourceExtensions(const QString&)’:
src/compiler.cpp:65:47: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  sourceExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                               ^~~~~~~~~~~~~~
src/compiler.cpp: In member function ‘void Compiler::setBytecodeExtensions(const QString&)’:
src/compiler.cpp:74:49: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  bytecodeExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                                 ^~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by ayalhw** [comment]
```pkg-config --modversion Qt5Core``` 结果是？

**Comment by ayalhw** [comment]
哦，我的锅，改完源码位置忘记改脚本

**Comment by ayalhw** [comment]
其实这两个是同一个问题来着（

**Comment by ayalhw** [comment]
最新 master 分支上的应该可以了。
真的很抱歉……
因为我本人的系统是 Arch，编译器和 Qt 版本都比较高，因此有很多东西我只能猜测着来，很难短时间内验证能否正常使用，
因此给您造成的麻烦我深感抱歉

**Comment by Bluequarks** [comment]
啊这,还是报错啊:
cmake --build .
[14/48] Building CXX object CMa...es/lemon.dir/src/compiler.cpp.o
FAILED: CMakeFiles/lemon.dir/src/compiler.cpp.o 
/usr/bin/c++  -DQAPPLICATION_CLASS=QApplication -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I. -Ilemon_autogen/include -Isrc -I3rdparty/SingleApplication -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -O3 -DNDEBUG   -fPIC -std=gnu++17 -MD -MT CMakeFiles/lemon.dir/src/compiler.cpp.o -MF CMakeFiles/lemon.dir/src/compiler.cpp.o.d -o CMakeFiles/lemon.dir/src/compiler.cpp.o -c src/compiler.cpp
src/compiler.cpp: In member function ‘void Compiler::setSourceExtensions(const QString&)’:
src/compiler.cpp:65:47: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  sourceExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                               ^~~~~~~~~~~~~~
src/compiler.cpp: In member function ‘void Compiler::setBytecodeExtensions(const QString&)’:
src/compiler.cpp:74:49: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  bytecodeExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                                 ^~~~~~~~~~~~~~
[15/48] Building CXX object CMa...es/lemon.dir/src/settings.cpp.o
FAILED: CMakeFiles/lemon.dir/src/settings.cpp.o 
/usr/bin/c++  -DQAPPLICATION_CLASS=QApplication -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I. -Ilemon_autogen/include -Isrc -I3rdparty/SingleApplication -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -O3 -DNDEBUG   -fPIC -std=gnu++17 -MD -MT CMakeFiles/lemon.dir/src/settings.cpp.o -MF CMakeFiles/lemon.dir/src/settings.cpp.o.d -o CMakeFiles/lemon.dir/src/settings.cpp.o -c src/settings.cpp
src/settings.cpp: In member function ‘void Settings::setInputFileExtensions(const QString&)’:
src/settings.cpp:251:50: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  inputFileExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                                  ^~~~~~~~~~~~~~
src/settings.cpp: In member function ‘void Settings::setOutputFileExtensions(const QString&)’:
src/settings.cpp:256:51: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  outputFileExtensions = extensions.split(";", Qt::SkipEmptyParts);
                                                   ^~~~~~~~~~~~~~
src/settings.cpp: In member function ‘void Settings::swapCompiler(int, int)’:
src/settings.cpp:294:17: error: ‘class QList<Compiler*>’ has no member named ‘swapItemsAt’
    compilerList.swapItemsAt(a, b);
                 ^~~~~~~~~~~
[19/48] Building CXX object CMa...Files/lemon.dir/src/lemon.cpp.o
ninja: build stopped: subcommand failed.
貌似是qt版本问题,没有SkipEmptyParts这个东西?还有几个swap没改全?

**Comment by Bluequarks** [comment]
啊这,我看了下readme把SkipEmpty内个替换了,然而又双叒报错了:
cmake --build .
[29/34] Building CXX object CMa.../lemon.dir/src/exportutil.cpp.o
FAILED: CMakeFiles/lemon.dir/src/exportutil.cpp.o 
/usr/bin/c++  -DQAPPLICATION_CLASS=QApplication -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I. -Ilemon_autogen/include -Isrc -I3rdparty/SingleApplication -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -O3 -DNDEBUG   -fPIC -std=gnu++17 -MD -MT CMakeFiles/lemon.dir/src/exportutil.cpp.o -MF CMakeFiles/lemon.dir/src/exportutil.cpp.o.d -o CMakeFiles/lemon.dir/src/exportutil.cpp.o -c src/exportutil.cpp
src/exportutil.cpp: In static member function ‘static void ExportUtil::exportCsv(QWidget*, Contest*, const QString&)’:
src/exportutil.cpp:825:50: error: ‘endl’ is not a member of ‘Qt’
  out << "\"" << tr("Total Score") << "\"" << Qt::endl;
                                                  ^~~~
src/exportutil.cpp:825:50: note: suggested alternatives:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtCore:54,
                 from src/exportutil.h:28,
                 from src/exportutil.cpp:27:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h:259:28: note:   ‘endl’
 Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                            ^~~~
In file included from /usr/include/c++/8/iterator:64,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:53,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
                 from src/exportutil.h:27,
                 from src/exportutil.cpp:27:
/usr/include/c++/8/ostream:590:5: note:   ‘std::endl’
     endl(basic_ostream<_CharT, _Traits>& __os)
     ^~~~
src/exportutil.cpp:855:40: error: ‘endl’ is not a member of ‘Qt’
    out << "\"" << score << "\"" << Qt::endl;
                                        ^~~~
src/exportutil.cpp:855:40: note: suggested alternatives:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtCore:54,
                 from src/exportutil.h:28,
                 from src/exportutil.cpp:27:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h:259:28: note:   ‘endl’
 Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                            ^~~~
In file included from /usr/include/c++/8/iterator:64,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:53,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
                 from src/exportutil.h:27,
                 from src/exportutil.cpp:27:
/usr/include/c++/8/ostream:590:5: note:   ‘std::endl’
     endl(basic_ostream<_CharT, _Traits>& __os)
     ^~~~
src/exportutil.cpp:859:48: error: ‘endl’ is not a member of ‘Qt’
    out << "\"" << tr("Invalid") << "\"" << Qt::endl;
                                                ^~~~
src/exportutil.cpp:859:48: note: suggested alternatives:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtCore:54,
                 from src/exportutil.h:28,
                 from src/exportutil.cpp:27:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h:259:28: note:   ‘endl’
 Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                            ^~~~
In file included from /usr/include/c++/8/iterator:64,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:53,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
                 from src/exportutil.h:27,
                 from src/exportutil.cpp:27:
/usr/include/c++/8/ostream:590:5: note:   ‘std::endl’
     endl(basic_ostream<_CharT, _Traits>& __os)
     ^~~~
[33/34] Building CXX object CMa..._autogen/mocs_compilation.cpp.o
ninja: build stopped: subcommand failed.
好像是Qt::endl的问题.本人不会Qt,提供不了帮助,dalao加油啊!

**Comment by ayalhw** [comment]
> 好像是Qt::endl的问题.本人不会Qt,提供不了帮助,dalao加油啊!

换成 ```std::endl``` 太草了……这个我居然没写进脚本……

**Comment by ayalhw** [comment]
什么时候大家都用 qt 5.15 啊（悲
~~（就让非 qt 5.15.1+ 用户忍受 konsole 开了缩放出现的白线吧（摔~~

**Comment by ayalhw** [comment]
对了……deepin v20 基于 Debian 10的话你可以试试 那个stable 的 deb 包，那个现在是debian10,也许能用
此外现在 master 分支的代码不再需要那些操作了……

**Comment by Bluequarks** [comment]
感谢dalao耐心解答,我把Qt::endl直接删了(简单粗暴(逃,然后编译出来了/xyx
目前测了两道,貌似没啥问题,dalao能说说会有啥影响吗,没啥大问题我懒得折腾了((

**Comment by Bluequarks** [comment]
> 什么时候大家都用 qt 5.15 啊（悲
> ~（就让非 qt 5.15.1+ 用户忍受 konsole 开了缩放出现的白线吧（摔~

不可能了,被三体星人锁死了((

**Comment by ayalhw** [comment]
请问可以正常使用了吗？

**Comment by Bluequarks** [comment]
完全正常!一个Error和Warning也没有! dalao太神了%%%
