### ISSUE TITLE
建议不忽略分值为 0 分的测试点

### ISSUE THREAD

**Issue by mrj1018** [iotang/Project_LemonLime#8]
如题，在测评含子任务捆绑的题目时，有时候子任务的测试点比较多，我想到这样一种实现方法。

```plain
测试点 1：apb.in.1b / apb.out.1b  0 分
测试点 2：apb.in.1c / apb.out.1c  0 分
测试点 3：apb.in.1d / apb.out.1d  0 分
测试点 4：apb.in.1a / apb.out.1a  10 分, 子任务依赖 1, 2, 3 测试点
```

理论上，这样就可以实现 `1a, 1b, 1c, 1d` 全部通过的情况下才可以拿到 10 分。

可是由于实际评测时 LemonLime 忽略了分值为 0 分的测试点（显示“被忽略”），导致无论能否通过 `1b, 1c, 1d` 测试点，只要通过了 `1a` 测试点，都可以拿到 10 分。

能否修改成不忽略分值为 0 分的测试点，使得这种子任务捆绑的实现方式能够正常工作呢？或者是否有更好的子任务捆绑的实现方式呢？

P.S. 有一种可能的方式是把总分分配到每个测试点上，如

```plain
测试点 1：apb.in.1b / apb.out.1b  1 分
测试点 2：apb.in.1c / apb.out.1c  1 分
测试点 3：apb.in.1d / apb.out.1d  1 分
测试点 4：apb.in.1a / apb.out.1a  7 分, 子任务依赖 1, 2, 3 测试点
```

但是如果点很多，每个点能分到的分数不足 1 分，似乎就不太行了；而且似乎也不太直观。

**Comment by iotang** [comment]
一种解决方案是，只忽略分值为 0 且最大分值大于 0 的测试点

**Comment by mrj1018** [comment]
> 一种解决方案是，只忽略分值为 0 且最大分值大于 0 的测试点

似乎不是很明白……“最大分值”指的是是这道题中的最大分值么？

或者也可以把忽略条件改成：

1. 这道题中有分值不为 0 的点
2. 这个点分值为 0，且没有被其他的点所子任务依赖

（二者同时满足）

另外，也许“子任务捆绑测试”的方法也可以补充进帮助文档（？）

**Comment by iotang** [comment]
锅已经补好了，通过评测状态（答案正确、答案部分正确什么的）来判断

不过因为要加个通信题支持，要过会再 push 上来
