### ISSUE TITLE
为什么移除了多线程评测的功能

### ISSUE THREAD

**Issue by riteme** [iotang/Project_LemonLime#9]
我个人觉得这个功能应该挺好的吧......是有其它的原因吗？

**Comment by Winlere** [comment]
多线程会导致评测性能不稳定，特别是复杂度很大或者时限不够宽松的时候...但这应该不是主要原因

**Comment by riteme** [comment]
@Winlere 确实可能有这种情况。感觉多线程评测会影响 cache 的性能？但我认为像例如 4 核 8 线程的这种 CPU，同时跑 3~4 个评测线程应该也是合理的。

**Comment by Dust1404** [comment]
主要是防止 subtask skip 的时候顺序乱掉，还有一个就是像楼上说的太不稳定了，并且有了 subtask skip 以后评测时间会大幅减少，多线程不太需要，于是就把删了。
